import torch.nn as nn
import torch
from typing import Tuple, Optional

'''
Pre-LN Transformer Sublayers for HW4P1 and HW4P2.

Three sublayers live here:
  1. SelfAttentionLayer  - causally masked self-attention (used in decoder)
  2. CrossAttentionLayer - cross-attention between decoder query and encoder key/value
  3. FeedForwardLayer    - two-layer FFN with GELU activation

All three use the Pre-LN (normalize first, then attend, then add residual) design.
This is more stable than the original Post-LN design from "Attention is All You Need".

Quick reminder of pre-norm flow:
    residual = x
    x = LayerNorm(x)
    x = SomeOperation(x)
    x = Dropout(x)
    x = residual + x
    return x
'''

## -------------------------------------------------------------------------------------------------
class SelfAttentionLayer(nn.Module):
    '''
    Pre-LN Decoder Sub-Layer 1.
    Causally masked self-attention. The decoder uses this to attend to its own
    previously generated tokens. The causal mask is passed in from outside
    (generated by CausalMask in masks.py) so we do not create it here.

    Attribute names are exactly: mha, norm, dropout
    The test suite checks these names directly so do not rename them.

    average_attn_weights=True means the attention weights returned have shape
    (B, T, T) averaged across heads, not (B, H, T, T). The tests expect (B, T, T).
    '''
    def __init__(self, d_model: int, num_heads: int, dropout: float = 0.0):
        '''
        Args:
            d_model   : model dimension (embedding size)
            num_heads : number of attention heads
            dropout   : dropout probability (applied after attention output)
        '''
        super().__init__()

        # multi-head attention module - this does the actual QKV computation
        # batch_first=True means input is (B, T, d_model) which is what we always use
        # average_attn_weights=True gives us shape (B, T, T) instead of (B, H, T, T)
        # this matters because the test suite checks the attention weight shape
        self.mha = nn.MultiheadAttention(
            embed_dim=d_model,
            num_heads=num_heads,
            dropout=0.0,       # attention-internal dropout, we handle outer dropout ourselves
            batch_first=True,
            average_attn_weights=True
        )

        # pre-norm layernorm - applied before the attention operation
        self.norm = nn.LayerNorm(d_model)

        # residual dropout - applied to the attention output before adding back the residual
        self.dropout = nn.Dropout(dropout)

    def forward(
        self,
        x: torch.Tensor,
        key_padding_mask: Optional[torch.Tensor] = None,
        attn_mask: Optional[torch.Tensor] = None
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        '''
        Args:
            x                : (B, T, d_model) - decoder input sequence
            key_padding_mask : (B, T) bool mask - True means "ignore this position"
            attn_mask        : (T, T) bool mask - causal mask, True means "do not attend here"

        Returns:
            x               : (B, T, d_model) - output after self-attention + residual
            attn_weights    : (B, T, T) - attention weights averaged across heads
        '''
        # save for the residual connection
        thierry_residual = x

        # normalize first (pre-LN), then attend
        x_normed = self.norm(x)

        # self-attention: Q, K, V all come from the same sequence (x_normed)
        # need_weights=True and average_attn_weights=True gives us (B, T, T) weights
        handel_attn_out, handel_weights = self.mha(
            query=x_normed,
            key=x_normed,
            value=x_normed,
            key_padding_mask=key_padding_mask,
            attn_mask=attn_mask,
            need_weights=True,
            average_attn_weights=True
        )

        # apply dropout and add residual
        x = thierry_residual + self.dropout(handel_attn_out)

        return x, handel_weights


## -------------------------------------------------------------------------------------------------
class CrossAttentionLayer(nn.Module):
    '''
    Pre-LN Decoder Sub-Layer 2.
    Cross-attention between the decoder and the encoder output.

    The key difference from SelfAttentionLayer:
      - Q comes from the decoder (x, the thing being generated)
      - K and V come from the encoder output (y, the speech representations)

    This is how the decoder "looks at" the speech encoder states when deciding
    what text token to generate next.

    Attribute names are exactly: mha, norm, dropout
    The test suite checks these names directly.
    '''
    def __init__(self, d_model: int, num_heads: int, dropout: float = 0.0):
        '''
        Args:
            d_model   : model dimension
            num_heads : number of attention heads
            dropout   : dropout probability
        '''
        super().__init__()

        # same setup as SelfAttentionLayer but will be used with Q != K/V
        self.mha = nn.MultiheadAttention(
            embed_dim=d_model,
            num_heads=num_heads,
            dropout=0.0,
            batch_first=True,
            average_attn_weights=True
        )

        # pre-norm on the decoder query before cross-attending
        self.norm = nn.LayerNorm(d_model)

        self.dropout = nn.Dropout(dropout)

    def forward(
        self,
        x: torch.Tensor,
        y: torch.Tensor,
        key_padding_mask: Optional[torch.Tensor] = None,
        attn_mask: Optional[torch.Tensor] = None
    ) -> Tuple[torch.Tensor, torch.Tensor]:
        '''
        Args:
            x                : (B, T_dec, d_model) - decoder hidden states (the query source)
            y                : (B, T_enc, d_model) - encoder hidden states (the key/value source)
            key_padding_mask : (B, T_enc) bool mask - True means "encoder position is padding"
            attn_mask        : (T_dec, T_enc) or None - rarely used in cross-attention

        Returns:
            x               : (B, T_dec, d_model) - output after cross-attention + residual
            attn_weights    : (B, T_dec, T_enc) - cross-attention weights
        '''
        # residual comes from the decoder stream (x), not the encoder (y)
        ishimwe_residual = x

        # normalize the decoder query before attending
        x_normed = self.norm(x)

        # cross-attention: Q from decoder, K and V from encoder
        henry_attn_out, henry_weights = self.mha(
            query=x_normed,
            key=y,
            value=y,
            key_padding_mask=key_padding_mask,
            attn_mask=attn_mask,
            need_weights=True,
            average_attn_weights=True
        )

        # dropout on the attention output, then add the decoder residual back
        x = ishimwe_residual + self.dropout(henry_attn_out)

        return x, henry_weights


## -------------------------------------------------------------------------------------------------
class FeedForwardLayer(nn.Module):
    '''
    Pre-LN Decoder Sub-Layer 3.
    Position-wise feed-forward network. Applied independently to each position.

    Architecture:
        LayerNorm -> Linear(d_model, d_ff) -> GELU -> Dropout -> Linear(d_ff, d_model)
    Then add residual.

    The ffn is stored as self.ffn (nn.Sequential) so that the from_pretrained_decoder
    method in transformers.py can load weights by key name matching.

    Attribute names are exactly: ffn, norm, dropout
    '''
    def __init__(self, d_model: int, d_ff: int, dropout: float = 0.0):
        '''
        Args:
            d_model : model dimension (input and output)
            d_ff    : inner dimension of the feedforward network (usually 4x d_model)
            dropout : dropout probability applied inside the FFN
        '''
        super().__init__()

        # the whole feedforward block as a Sequential so weight keys match the
        # expected pattern when loading pretrained decoder weights for P2
        self.ffn = nn.Sequential(
            nn.Linear(d_model, d_ff),   # expand
            nn.GELU(),                   # activation (GELU not ReLU, important!)
            nn.Dropout(dropout),         # inner dropout
            nn.Linear(d_ff, d_model),   # contract back
        )

        # pre-norm
        self.norm = nn.LayerNorm(d_model)

        # residual dropout applied after the FFN output
        self.dropout = nn.Dropout(dropout)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        '''
        Args:
            x : (B, T, d_model) - input

        Returns:
            x : (B, T, d_model) - output after FFN + residual
        '''
        handel_residual = x

        # normalize first, then run through the FFN
        x = handel_residual + self.dropout(self.ffn(self.norm(x)))

        return x
